In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.shape

(250, 302)

In [4]:
test.shape

(19750, 301)

In [5]:
train.head()

id  target      0      1      2      3      4      5      6      7  ...    \
0   0     1.0 -0.098  2.165  0.681 -0.614  1.309 -0.455 -0.236  0.276  ...     
1   1     0.0  1.081 -0.973 -0.383  0.326 -0.428  0.317  1.172  0.352  ...     
2   2     1.0 -0.523 -0.089 -0.348  0.148 -0.022  0.404 -0.023 -0.172  ...     
3   3     1.0  0.067 -0.021  0.392 -1.637 -0.446 -0.725 -1.035  0.834  ...     
4   4     1.0  2.347 -0.831  0.511 -0.021  1.225  1.594  0.585  1.509  ...     

     290    291    292    293    294    295    296    297    298    299  
0  0.867  1.347  0.504 -0.649  0.672 -2.097  1.051 -0.414  1.038 -1.065  
1 -0.165 -1.695 -1.257  1.359 -0.808 -1.624 -0.458 -1.099 -0.936  0.973  
2  0.013  0.263 -1.222  0.726  1.444 -1.165 -1.544  0.004  0.800 -1.211  
3 -0.404  0.640 -0.595 -0.966  0.900  0.467 -0.562 -0.254 -0.533  0.238  
4  0.898  0.134  2.415 -0.996 -1.006  1.378  1.246  1.478  0.428  0.253  

[5 rows x 302 columns]

In [6]:
train.isnull().sum()

id        0
target    0
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
         ..
270       0
271       0
272       0
273       0
274       0
275       0
276       0
277       0
278       0
279       0
280       0
281       0
282       0
283       0
284       0
285       0
286       0
287       0
288       0
289       0
290       0
291       0
292       0
293       0
294       0
295       0
296       0
297       0
298       0
299       0
Length: 302, dtype: int64

In [7]:
y_train = train["target"]

In [8]:
X_test = test.drop(["id"],axis=1)

In [9]:
X_train = train.drop(["target","id"],axis=1)

In [10]:
X_train.head()

0      1      2      3      4      5      6      7      8      9  \
0 -0.098  2.165  0.681 -0.614  1.309 -0.455 -0.236  0.276 -2.246  1.825   
1  1.081 -0.973 -0.383  0.326 -0.428  0.317  1.172  0.352  0.004 -0.291   
2 -0.523 -0.089 -0.348  0.148 -0.022  0.404 -0.023 -0.172  0.137  0.183   
3  0.067 -0.021  0.392 -1.637 -0.446 -0.725 -1.035  0.834  0.503  0.274   
4  2.347 -0.831  0.511 -0.021  1.225  1.594  0.585  1.509 -0.012  2.198   

   ...      290    291    292    293    294    295    296    297    298    299  
0  ...    0.867  1.347  0.504 -0.649  0.672 -2.097  1.051 -0.414  1.038 -1.065  
1  ...   -0.165 -1.695 -1.257  1.359 -0.808 -1.624 -0.458 -1.099 -0.936  0.973  
2  ...    0.013  0.263 -1.222  0.726  1.444 -1.165 -1.544  0.004  0.800 -1.211  
3  ...   -0.404  0.640 -0.595 -0.966  0.900  0.467 -0.562 -0.254 -0.533  0.238  
4  ...    0.898  0.134  2.415 -0.996 -1.006  1.378  1.246  1.478  0.428  0.253  

[5 rows x 300 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [14]:
log_clf = LogisticRegression(random_state = 42)
param_grid={ 'class_weight': ['balanced', None],
              'C':[0.001, 0.01, 0.1, 1, 10, 100, 1000],
             'solver' : ['liblinear'],
              'penalty':['l1','l2'],
              'max_iter':range(100,1000,100),
              'tol':np.arange(0.01,0.10,0.01)
           }
grid=GridSearchCV(log_clf,param_grid = param_grid , scoring = 'roc_auc', verbose = 1, n_jobs = -1)
grid.fit(X_train,y_train)

print("Best Score:" + str(grid.best_score_))
print("Best Parameters: " + str(grid.best_params_))

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 3 folds for each of 2268 candidates, totalling 6804 fits


[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   19.8s
[Parallel(n_jobs=-1)]: Done 3722 tasks      | elapsed:   37.5s


Best Score:0.8098431865828092
Best Parameters: {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear', 'tol': 0.03}


[Parallel(n_jobs=-1)]: Done 6804 out of 6804 | elapsed:   53.2s finished
c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [16]:
log_clf = LogisticRegression(C=0.1,random_state=42,class_weight='balanced',penalty='l1',solver='liblinear',tol=0.02,verbose=0)
log_clf.fit(X_train,y_train)

LogisticRegression(C=0.1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l1', random_state=42,
          solver='liblinear', tol=0.02, verbose=0, warm_start=False)

In [17]:
pred_log=log_clf.predict(X_test)
pred_log

array([1., 0., 1., ..., 0., 1., 0.])

In [18]:
submission1 = pd.read_csv("sample_submission.csv")
submission1["target"] = pred_log
submission1.to_csv("submissionlog.csv",index = False)

In [19]:
from sklearn.feature_selection import RFE

In [23]:
selector = RFE(log_clf, 25, step=1)
selector.fit(X_train,y_train)

RFE(estimator=LogisticRegression(C=0.1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l1', random_state=42,
          solver='liblinear', tol=0.02, verbose=0, warm_start=False),
  n_features_to_select=25, step=1, verbose=0)

In [25]:
pred_RFE = selector.predict(X_test)
pred_RFE

array([1., 0., 1., ..., 0., 1., 0.])

In [30]:
submission2 = pd.read_csv("sample_submission.csv")
submission2["target"] = pred_RFE
submission2.to_csv("submissionRFE.csv",index = False)

In [26]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(random_state=42)
param_grid1={ 'min_samples_split' : range(10,500,20),
              'max_depth': range(1,20,2)
           }
grid=GridSearchCV(tree_model,param_grid = param_grid1 , scoring = 'roc_auc', verbose = 1, n_jobs = -1)
grid.fit(X_train,y_train)

print("Best Score:" + str(grid.best_score_))
print("Best Parameters: " + str(grid.best_params_))

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 3 folds for each of 250 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Done  48 tasks      | elapsed:   15.0s


Best Score:0.6559220125786162
Best Parameters: {'max_depth': 1, 'min_samples_split': 10}


[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:   18.3s finished
c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [27]:
tree_model = DecisionTreeClassifier(max_depth=1,min_samples_split=10,random_state=42)
tree_model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [29]:
pred_tree = tree_model.predict(X_test)
pred_tree

array([1., 1., 0., ..., 0., 1., 1.])

In [31]:
submission3 = pd.read_csv("sample_submission.csv")
submission3["target"] = pred_tree
submission3.to_csv("submissiontree.csv",index = False)

In [33]:
from sklearn.linear_model import Lasso
lasoreg =Lasso()
param_grid1={ "alpha" : np.arange(0.0, 1.0, 0.02)
             
            }
grid=GridSearchCV(lasoreg,param_grid = param_grid1 , scoring = 'roc_auc', cv=10,verbose = 1, n_jobs = -1)
grid.fit(X_train,y_train)

print("Best Score:" + str(grid.best_score_))
print("Best Parameters: " + str(grid.best_params_))


Fitting 10 folds for each of 50 candidates, totalling 500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 274 tasks      | elapsed:    1.4s


Best Score:0.7997462143120038
Best Parameters: {'alpha': 0.04}


[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    2.2s finished


In [34]:
lasoreg = Lasso(alpha=0.06, normalize=True)
lasoreg.fit(X_train,y_train)

Lasso(alpha=0.06, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [35]:
pred_laso = lasoreg.predict(X_test)
pred_laso

array([0.64, 0.64, 0.64, ..., 0.64, 0.64, 0.64])

In [36]:
submission4 = pd.read_csv("sample_submission.csv")
submission4["target"] = pred_laso
submission4.to_csv("submissionlaso.csv",index = False)

In [37]:
submission1.head()

id  target
0  250     1.0
1  251     0.0
2  252     1.0
3  253     1.0
4  254     0.0

In [38]:
submission2.head()

id  target
0  250     1.0
1  251     0.0
2  252     1.0
3  253     1.0
4  254     0.0

In [39]:
submission3.head()

id  target
0  250     1.0
1  251     1.0
2  252     0.0
3  253     1.0
4  254     1.0

In [40]:
submission4.head()

id  target
0  250    0.64
1  251    0.64
2  252    0.64
3  253    0.64
4  254    0.64